# 服务端口
server:
  port: 9004

spring:
  application:
    # 服务名
    name: vod-service
  profiles:
    # 环境设置：dev、test、prod
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848
  redis:
    host: 115.29.193.74
    port: 6379
    password: 0751@@@wjw
    database: 0
    timeout: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        min-idle: 0

# 阿里云 vod
aliyun:
  vod:
    file:
      keyid: LTAI5tMy2iXWoR39QuqKaSbk
      keysecret: cKx0YIUSpvN15hdrNkLcAzrGO332Jj
