server:
  port: 9003
spring:
  application:
    name: upload-service
#  profiles:
#    active: dev
  servlet:
    multipart:
      max-file-size: 10MB   # 限制文件上传的大小
  redis:
    host: 115.29.193.74
    port: 6379
    password: 0751@@@wjw
    database: 0
    timeout: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        min-idle: 0

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 115.29.193.74:22122

domain:
  http://image.wjw.today/