server:
  port: 9000

spring:
  application:
    name: job-service
  profiles:
    active: dev   #TODO 发布的时候修改环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freework?serverTimezone=GMT%2B8
    username: root
    password: 0751@@@wjw
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848
  redis:
#    host: 115.29.193.74
#    password: 0751@@@wjw
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        min-idle: 0
#mybatis日志，配置log4j或者logback后可以删掉
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:com/wjw/job/mapper/xml/*.xml

#开启熔断机制
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置hystrix超时时间，默认1000ms
            timeoutInMilliseconds: 10000