server:
  port: 9005
spring:
  application:
    name: sms-service
  profiles:
    active: dev   #TODO 发布的时候修改环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freework?serverTimezone=GMT%2B8
    username: root
    password: 0751@@@wjw
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
#    host: 115.29.193.74
#    password: 0751@@@wjw
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        min-idle: 0

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/wjw/job/mapper/xml/*.xml

freework:
  sms:
    accessKeyId: LTAI5tMy2iXWoR39QuqKaSbk # 你自己的accessKeyId
    accessKeySecret: cKx0YIUSpvN15hdrNkLcAzrGO332Jj # 你自己的AccessKeySecret
    signName: wjw商城 # 签名名称
    verifyCodeTemplate: SMS_196643222 # 模板code